<<<<<<< HEAD
# Generated by Django 5.2.6 on 2025-10-02 19:08
=======
# Generated by Django 5.2.6 on 2025-10-02 19:04
>>>>>>> 64dd8d76bdd621700a1c706eba5f6b73455cb5c6

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('chat_message_id', models.AutoField(primary_key=True, serialize=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('Role', models.CharField(default='', max_length=50)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notif_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_sent', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('due_date', models.DateField()),
                ('cm_id', models.IntegerField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('project_name', models.CharField(max_length=100)),
                ('project_description', models.TextField(blank=True, null=True)),
                ('created_on', models.DateField()),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('security_question', models.CharField(max_length=255)),
                ('security_answer', models.CharField(max_length=255)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('meeting_id', models.AutoField(primary_key=True, serialize=False)),
                ('meeting_title', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField()),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='pcp_webapp.project')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProjectChat',
            fields=[
                ('project_chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('chat_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcp_webapp.chatmessage')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcp_webapp.project')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProjectLinks',
            fields=[
                ('link_id', models.AutoField(primary_key=True, serialize=False)),
                ('link_url', models.URLField(max_length=500)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='pcp_webapp.project')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=100)),
                ('task_description', models.TextField(blank=True, null=True)),
                ('task_due_date', models.DateField()),
                ('task_status', models.CharField(max_length=50)),
                ('task_priority', models.CharField(max_length=50)),
                ('is_final_submission', models.BooleanField(default=False)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcp_webapp.project')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='pcp_webapp.task')),
            ],
        ),
        migrations.CreateModel(
            name='EditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_requests', to='pcp_webapp.task')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('direct', 'Direct Message'), ('project', 'Project Message'), ('system', 'System Notification')], default='direct', max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='pcp_webapp.project')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='pcp_webapp.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='pcp_webapp.user')),
            ],
            options={
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_title', models.CharField(max_length=200)),
                ('document_description', models.TextField(blank=True, null=True)),
                ('date_time_uploaded', models.DateTimeField(default=django.utils.timezone.now)),
                ('doc_type', models.CharField(max_length=500)),
                ('date_time_last_modified', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='documents/')),
                ('task_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pcp_webapp.task')),
                ('last_modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcp_webapp.user')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcp_webapp.user'),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('project_created', 'Project Created'), ('project_updated', 'Project Updated'), ('task_created', 'Task Created'), ('task_updated', 'Task Updated'), ('task_completed', 'Task Completed'), ('document_uploaded', 'Document Uploaded'), ('member_added', 'Member Added'), ('member_removed', 'Member Removed')], max_length=30)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='pcp_webapp.project')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='pcp_webapp.user')),
            ],
            options={
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User_Task',
            fields=[
                ('user_task_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcp_webapp.user')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcp_webapp.task')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('user_notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcp_webapp.user')),
                ('notif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcp_webapp.notification')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('user_project_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=50)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pcp_webapp.user')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcp_webapp.project')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
