# Generated by Django 5.2.6 on 2025-09-22 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcp_webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('cm_id', models.AutoField(primary_key=True, serialize=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('status', models.CharField(default='sent', max_length=20)),
            ],
            options={
                'db_table': 'CHAT_MESSAGE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProjectChat',
            fields=[
                ('pc_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'PROJECT_CHAT',
                'managed': True,
            },
        ),
        migrations.RemoveConstraint(
            model_name='userproject',
            name='user_project_pk',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcp_webapp.user'),
        ),
        migrations.AddField(
            model_name='projectchat',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcp_webapp.project'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='user_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcp_webapp.projectchat'),
        ),
    ]
