# Generated by Django 5.2.6 on 2025-09-29 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcp_webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='grades',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='requested_by',
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('user_notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcp_webapp.user')),
                ('notif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcp_webapp.notification')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
