# Generated by Django 5.2.6 on 2025-09-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcp_webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(max_length=500),
        ),
    ]
