# Generated by Django 5.2.6 on 2025-09-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcp_webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(db_column='project_id', primary_key=True, serialize=False)),
                ('due_date', models.DateField(db_column='due_date')),
                ('cm_id', models.IntegerField(db_column='cm_id')),
                ('feedback', models.TextField(db_column='feedback', null=True)),
                ('grade', models.IntegerField(db_column='grade', null=True)),
                ('project_name', models.CharField(db_column='project_name', max_length=100)),
                ('project_description', models.TextField(db_column='project_description', null=True)),
                ('created_on', models.DateField(db_column='created_on')),
            ],
            options={
                'db_table': 'project',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='user',
            table='pcpuser',
        ),
    ]
