# Generated by Django 5.2.6 on 2025-09-18 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcp_webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userproject',
            name='user_project_pk',
        ),
    ]
