# Generated by Django 5.2.6 on 2025-09-28 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcp_webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_task',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcp_webapp.task'),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('chat_message_id', models.AutoField(primary_key=True, serialize=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('Project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pcp_webapp.project')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcp_webapp.user')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProjectChat',
            fields=[
                ('project_chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('chat_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcp_webapp.chatmessage')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcp_webapp.project')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
