# Generated by Django 5.2.6 on 2025-10-01 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcp_webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_task',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcp_webapp.user'),
        ),
    ]
