# Generated by Django 5.2.6 on 2025-09-19 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcp_webapp', '0002_remove_userproject_user_project_pk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=100)),
                ('task_description', models.TextField(blank=True, null=True)),
                ('task_due_date', models.DateField()),
                ('task_status', models.CharField(max_length=50)),
                ('task_priority', models.CharField(max_length=50)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pcp_webapp.project')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User_Task',
            fields=[
                ('user_task_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pcp_webapp.user')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pcp_webapp.task')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
