# Generated by Django 5.2.6 on 2025-09-23 16:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcp_webapp', '0002_alter_document_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('due_date', models.DateField()),
                ('cm_id', models.IntegerField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('project_name', models.CharField(max_length=100)),
                ('project_description', models.TextField(blank=True, null=True)),
                ('created_on', models.DateField()),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'managed': True, 'ordering': ['-datetime_uploaded']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'managed': True},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='task_description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
        migrations.AddField(
            model_name='task',
            name='task_due_date',
            field=models.DateField(default=datetime.datetime(2025, 9, 23, 16, 4, 37, 781027, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='task_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='task',
            name='task_name',
            field=models.CharField(default='Untitled Task', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='task_priority',
            field=models.CharField(default='Medium', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='task_status',
            field=models.CharField(default='Pending', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pcp_webapp.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='project_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='pcp_webapp.project'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='User_Task',
            fields=[
                ('user_task_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pcp_webapp.user')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pcp_webapp.task')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('user_project_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=50)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pcp_webapp.user')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pcp_webapp.project')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
