# Generated by Django 5.2.6 on 2025-09-22 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcp_webapp', '0002_remove_userproject_user_project_pk'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectChat',
            fields=[
                ('pc_id', models.AutoField(primary_key=True, serialize=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcp_webapp.project')),
            ],
            options={
                'db_table': 'PROJECT_CHAT',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('cm_id', models.AutoField(primary_key=True, serialize=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('status', models.CharField(default='sent', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcp_webapp.user')),
                ('user_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcp_webapp.projectchat')),
            ],
            options={
                'db_table': 'CHAT_MESSAGE',
                'managed': True,
            },
        ),
    ]
