# Generated by Django 5.2.6 on 2025-10-01 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcp_webapp', '0002_alter_user_task_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproject',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcp_webapp.project'),
        ),
    ]
