# Generated by Django 5.2.6 on 2025-09-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcp_webapp', '0002_alter_user_task_task_id_chatmessage_projectchat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='Project',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='Role',
            field=models.CharField(default='', max_length=50),
        ),
    ]
