# Generated by Django 5.2.6 on 2025-10-01 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcp_webapp', '0003_alter_userproject_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_final_submission',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcp_webapp.project'),
        ),
    ]
